---
title: K Sreeman Reddy
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: sreemanmohanreddy@gmail.com
description: 'I am an undergradute student who wonders about this marvellous universe.

'
about_me: "I am an undergraduate studying at IIT Bombay. I like physics and maths.
  I am from Tadipatri, Andhra Pradesh. \n"
baseurl: ''
url: https://iamsreeman.github.io/
linked_in_link: https://www.linkedin.com/in/iamsreeman/
github_link: https://www.github.com/iamsreeman
facebook_link: https://facebook.com/iamsreeman
twitter_link: https://twitter.com/iamsreeman
google_analytics_id: UA-165988854-1
select_options: clear-filters HTML5 CSS3 SCSS javaScript jQuery materialize charts.js
  React jekyll Ruby-on-Rails Sinatra front-end back-end finished current
sass:
  sass_dir: assets/css/main.css
  style: :nested
gems:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
